name:                satanf
version:             0.1.0.0
github:              "ignaciobll/satanf"
license:             BSD3
author:              "Ignacio Ballesteros"
maintainer:          "ignacioballesterosgonzalez@gmail.com"
copyright:           "2020 Ignacio Ballesteros"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/ignaciobll/satanf#readme>

dependencies:
- base >= 4.7 && < 5
- wl-pprint
- megaparsec
- parsec
- hspec
- optparse-applicative
- Cabal
- mod
- vector
- containers
- QuickCheck
- criterion
- deepseq
- matrix
- hashable
- perfect-hash-generator
- bits
- Smtlib
- OpenCL
- CLUtil
- language-c-quote
- mainland-pretty

library:
  source-dirs: src

executables:
  satanf:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -O2
    dependencies:
    - satanf

  satanf-clinfo:
    main:                CLInfo.hs
    source-dirs:         app
    ghc-options:
    - -main-is CLInfo
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    # - -O2
    dependencies:
    - satanf

  satanf-vector:
    main:               CLVectorSample.hs
    source-dirs:        app
    ghc-options:
    - -main-is CLVectorSample
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    # - -O2
    dependencies:
    - satanf

  satanf-interactive:
    main:               Interactive.hs
    source-dirs:        app
    ghc-options:
    - -main-is Interactive
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    # - -O2
    dependencies:
    - satanf



tests:
  satanf-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - satanf
