* Related Tools

** Bosphorus

https://github.com/meelgroup/bosphorus

#+begin_quote
Bosphorus is an ANF simplification and solving tool. It takes as input an ANF
over GF(2) and can simplify and solve it. It uses many different algorithms,
including XL, SAT, Brickenstein's ANF-to-CNF conversion, Gauss-Jordan
elimination, etc. to simplify and solve ANFs.

The main use of the system is to simplify and solve ANF problems. It should give
you highly optimised ANFs and CNFs that it can solve. Its ANF simplifications
should be useful is many areas, not just direct ANF-to-SAT solving. For example,
it could be useful for helping to break post-quantum cryptograpy problems.

This work was done by Davin Choo and Kian Ming A. Chai from DSO National
Laboratories Singapore, and Mate Soos and Kuldeep Meel from the National
University of Singapore (NUS). If you use Bosphorus, please cite our paper
(bibtex) published at DATE 2019. Some of the code was generously donated by
Security Research Labs, Berlin.
#+end_quote
